spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/mutsa_shop?characterEncoding=UTF-8&serverTimezone=Asia/Seoul}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never


jwt:
  secret: ${JWT_SECRET:likeLionMutsaShoppingMallBackendProjectSecretKey20260712!}
  expiration: 3600000